#!/bin/bash

selected=$(find ~/Development/projects/ ~/Development/intellectsoft/ -maxdepth 1 -mindepth 1 -type d | fzf) || exit 1 
selected_name=$(basename "$selected" | tr . _)

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$selected_name" -c "$selected" "nvim;bash"
  tmux new-window -d -t "${selected_name}" -c "${selected}"
  tmux new-window -d -t "${selected_name}" -c "${selected}"
  return
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected" "nvim;bash"
  tmux new-window -d -t "${selected_name}" -c "${selected}"
  tmux new-window -d -t "${selected_name}" -c "${selected}"
fi

[[ -z $TMUX ]] && tmux attach -t "$selected_name" || tmux switch-client -t "$selected_name"
