#!/bin/sh
set -eu

project_dirs=(
  "$HOME/Development/projects/"
  "$HOME/Development/intellectsoft/"
)

project_list=$(find "${project_dirs[@]}" -maxdepth 1 -mindepth 1 -xtype d 2>/dev/null)
project_list_base=$(echo "${project_list}" | xargs -n1 basename)
selected=$(echo "${project_list_base}" | fzf)

selected_path=""
for dir in "${project_dirs[@]}"; do
  for file in "$dir"*; do
    if [[ -d "$file" ]] && [[ $(basename "$file") == "$selected" ]]; then
      selected_path="$file"
      break 2
    fi
  done
done

selected_name=$(basename "$selected" | sed 's/[^a-zA-Z0-9_-]/_/g')

tmux_clients=$(tmux list-clients 2>/dev/null | wc -l) || tmux_clients=0

create_tmux_session() {
  local session_name="$1"
  local session_path="$2"
  tmux new-session -ds "$session_name" -c "$session_path" "nvim;nvim;nvim;nvim;nvim;nivm;nvim;nvim;nvim;nvim;nvim;nivm;nvim;nvim;nvim"
  tmux new-window -d -t "$session_name" -c "$session_path"
  tmux new-window -d -t "$session_name" -c "$session_path"
  tmux select-window -t "$session_name:0"
}

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
  create_tmux_session "$selected_name" "$selected_path"
fi

if [[ "$tmux_clients" -eq 0 ]]; then
  tmux attach-session -t "$selected_name"
else
  tmux switch-client -t "$selected_name"
fi
