[window]
title = "Alacritty"
blur = true
opacity = 0.9
padding.x = 1

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape= "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "IosevkaNerdFont"
bold.family = "IosevkaNerdFont"
italic.family = "IosevkaNerdFont"
bold_italic.family = "IosevkaNerdFont"
offset.x = 0
offset.y = 0
size = 3.4

[general]
live_config_reload = true
working_directory = "None"

# [colors.primary]
# background = "#24273a"
# foreground = "#cad3f5"
# dim_foreground = "#8087a2"
# bright_foreground = "#cad3f5"

# [colors.cursor]
# text = "#24273a"
# cursor = "#f4dbd6"
#
# [colors.vi_mode_cursor]
# text = "#24273a"
# cursor = "#b7bdf8"
#
# [colors.search.matches]
# foreground = "#24273a"
# background = "#a5adcb"
#
# [colors.search.focused_match]
# foreground = "#24273a"
# background = "#a6da95"
#
# [colors.footer_bar]
# foreground = "#24273a"
# background = "#a5adcb"
#
# [colors.hints.start]
# foreground = "#24273a"
# background = "#eed49f"
#
# [colors.hints.end]
# foreground = "#24273a"
# background = "#a5adcb"
#
# [colors.selection]
# text = "#24273a"
# background = "#f4dbd6"
#
# [colors.normal]
# black = "#494d64"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#b8c0e0"
#
# [colors.bright]
# black = "#5b6078"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#a5adcb"
#
# [colors.dim]
# black = "#494d64"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#b8c0e0"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#f5a97f"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f4dbd6"

[colors.primary]
foreground = "#e0def4"
background = "#232136"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[colors.cursor]
text = "#e0def4"
cursor = "#7c78a3"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#56526e"

[colors.search.matches]
foreground = "#908caa"
background = "#393552"

[colors.search.focused_match]
foreground = "#232136"
background = "#ea9a97"

[colors.hints.start]
foreground = "#908caa"
background = "#2a273f"

[colors.hints.end]
foreground = "#6e6a86"
background = "#2a273f"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#2a273f"

[colors.selection]
text = "#e0def4"
background = "#44415a"

[colors.normal]
black = "#393552"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"

[colors.dim]
black = "#6e6a86"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"

